version: "3.9"

services:
  exchange:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange
    command: sh -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/exchange
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: exchange_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: exchange_redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
